<?php

	// ########################## INCLUDE BACK-END ###########################
	require_once (dirname(dirname(dirname(__FILE__))) . DIRECTORY_SEPARATOR . 'cache' . DIRECTORY_SEPARATOR . 'data_admin_options.php');
	
	$path = $base_url . "includes/emojis/img/32/";

?>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>231a.png" alt="" data-id="231a.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f4f1.png" alt="" data-id="1f4f1.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f4f2.png" alt="" data-id="1f4f2.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f4bb.png" alt="" data-id="1f4bb.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f4bd.png" alt="" data-id="1f4bd.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f4be.png" alt="" data-id="1f4be.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f4bf.png" alt="" data-id="1f4bf.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f4c0.png" alt="" data-id="1f4c0.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f4fc.png" alt="" data-id="1f4fc.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f4f7.png" alt="" data-id="1f4f7.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f4f9.png" alt="" data-id="1f4f9.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f3a5.png" alt="" data-id="1f3a5.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f4de.png" alt="" data-id="1f4de.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>260e.png" alt="" data-id="260e.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f4df.png" alt="" data-id="1f4df.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f4e0.png" alt="" data-id="1f4e0.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f4fa.png" alt="" data-id="1f4fa.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f4fb.png" alt="" data-id="1f4fb.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>23f0.png" alt="" data-id="23f0.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>231b.png" alt="" data-id="231b.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>23f3.png" alt="" data-id="23f3.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f4e1.png" alt="" data-id="1f4e1.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f50b.png" alt="" data-id="1f50b.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f50c.png" alt="" data-id="1f50c.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f4a1.png" alt="" data-id="1f4a1.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f526.png" alt="" data-id="1f526.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f4b8.png" alt="" data-id="1f4b8.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f4b5.png" alt="" data-id="1f4b5.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f4b4.png" alt="" data-id="1f4b4.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f4b6.png" alt="" data-id="1f4b6.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f4b7.png" alt="" data-id="1f4b7.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f4b0.png" alt="" data-id="1f4b0.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f4b3.png" alt="" data-id="1f4b3.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f48e.png" alt="" data-id="1f48e.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f527.png" alt="" data-id="1f527.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f528.png" alt="" data-id="1f528.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f529.png" alt="" data-id="1f529.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f52b.png" alt="" data-id="1f52b.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f4a3.png" alt="" data-id="1f4a3.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f52a.png" alt="" data-id="1f52a.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f6ac.png" alt="" data-id="1f6ac.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f52e.png" alt="" data-id="1f52e.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f488.png" alt="" data-id="1f488.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f52d.png" alt="" data-id="1f52d.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f52c.png" alt="" data-id="1f52c.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f48a.png" alt="" data-id="1f48a.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f489.png" alt="" data-id="1f489.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f516.png" alt="" data-id="1f516.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f6bd.png" alt="" data-id="1f6bd.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f6bf.png" alt="" data-id="1f6bf.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f6c0.png" alt="" data-id="1f6c0.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f6c1.png" alt="" data-id="1f6c1.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f511.png" alt="" data-id="1f511.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f6aa.png" alt="" data-id="1f6aa.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f5ff.png" alt="" data-id="1f5ff.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f388.png" alt="" data-id="1f388.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f38f.png" alt="" data-id="1f38f.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f380.png" alt="" data-id="1f380.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f381.png" alt="" data-id="1f381.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f38a.png" alt="" data-id="1f38a.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f389.png" alt="" data-id="1f389.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f38e.png" alt="" data-id="1f38e.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f390.png" alt="" data-id="1f390.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f38c.png" alt="" data-id="1f38c.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f3ee.png" alt="" data-id="1f3ee.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>2709.png" alt="" data-id="2709.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f4e9.png" alt="" data-id="1f4e9.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f4e8.png" alt="" data-id="1f4e8.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f48c.png" alt="" data-id="1f48c.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f4e7.png" alt="" data-id="1f4e7.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f4ee.png" alt="" data-id="1f4ee.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f4ea.png" alt="" data-id="1f4ea.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f4eb.png" alt="" data-id="1f4eb.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f4ec.png" alt="" data-id="1f4ec.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f4ed.png" alt="" data-id="1f4ed.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f4e6.png" alt="" data-id="1f4e6.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f4ef.png" alt="" data-id="1f4ef.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f4e5.png" alt="" data-id="1f4e5.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f4e4.png" alt="" data-id="1f4e4.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f4dc.png" alt="" data-id="1f4dc.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f4c3.png" alt="" data-id="1f4c3.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f4d1.png" alt="" data-id="1f4d1.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f4ca.png" alt="" data-id="1f4ca.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f4c8.png" alt="" data-id="1f4c8.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f4c9.png" alt="" data-id="1f4c9.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f4c4.png" alt="" data-id="1f4c4.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f4c5.png" alt="" data-id="1f4c5.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f4c6.png" alt="" data-id="1f4c6.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f4c7.png" alt="" data-id="1f4c7.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f4cb.png" alt="" data-id="1f4cb.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f4c1.png" alt="" data-id="1f4c1.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f4c2.png" alt="" data-id="1f4c2.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f4f0.png" alt="" data-id="1f4f0.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f4d3.png" alt="" data-id="1f4d3.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f4d5.png" alt="" data-id="1f4d5.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f4d7.png" alt="" data-id="1f4d7.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f4d8.png" alt="" data-id="1f4d8.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f4d9.png" alt="" data-id="1f4d9.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f4d4.png" alt="" data-id="1f4d4.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f4d2.png" alt="" data-id="1f4d2.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f4da.png" alt="" data-id="1f4da.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f4d6.png" alt="" data-id="1f4d6.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f517.png" alt="" data-id="1f517.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f4ce.png" alt="" data-id="1f4ce.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>2702.png" alt="" data-id="2702.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f4d0.png" alt="" data-id="1f4d0.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f4cf.png" alt="" data-id="1f4cf.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f4cc.png" alt="" data-id="1f4cc.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f4cd.png" alt="" data-id="1f4cd.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f6a9.png" alt="" data-id="1f6a9.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f510.png" alt="" data-id="1f510.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f512.png" alt="" data-id="1f512.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f513.png" alt="" data-id="1f513.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f50f.png" alt="" data-id="1f50f.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>2712.png" alt="" data-id="2712.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f4dd.png" alt="" data-id="1f4dd.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>270f.png" alt="" data-id="270f.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f50d.png" alt="" data-id="1f50d.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f50e.png" alt="" data-id="1f50e.png" /></div>