<?php

	// ########################## INCLUDE BACK-END ###########################
	require_once (dirname(dirname(dirname(__FILE__))) . DIRECTORY_SEPARATOR . 'cache' . DIRECTORY_SEPARATOR . 'data_admin_options.php');
	
	$path = $base_url . "includes/emojis/img/32/";

?>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>2764.png" alt="" data-id="2764.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f49b.png" alt="" data-id="1f49b.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f49a.png" alt="" data-id="1f49a.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f499.png" alt="" data-id="1f499.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f494.png" alt="" data-id="1f494.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f49c.png" alt="" data-id="1f49c.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f495.png" alt="" data-id="1f495.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f493.png" alt="" data-id="1f493.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f49e.png" alt="" data-id="1f49e.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f497.png" alt="" data-id="1f497.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f498.png" alt="" data-id="1f498.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f496.png" alt="" data-id="1f496.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f49d.png" alt="" data-id="1f49d.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f49f.png" alt="" data-id="1f49f.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f52f.png" alt="" data-id="1f52f.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>26ce.png" alt="" data-id="26ce.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>2648.png" alt="" data-id="2648.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>2649.png" alt="" data-id="2649.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>264a.png" alt="" data-id="264a.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>264b.png" alt="" data-id="264b.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>264c.png" alt="" data-id="264c.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>264d.png" alt="" data-id="264d.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>264e.png" alt="" data-id="264e.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>264f.png" alt="" data-id="264f.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>2650.png" alt="" data-id="2650.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>2651.png" alt="" data-id="2651.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>2652.png" alt="" data-id="2652.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>2653.png" alt="" data-id="2653.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f194.png" alt="" data-id="1f194.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f4f4.png" alt="" data-id="1f4f4.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f4f3.png" alt="" data-id="1f4f3.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f237.png" alt="" data-id="1f237.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f19a.png" alt="" data-id="1f19a.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f4ae.png" alt="" data-id="1f4ae.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f170.png" alt="" data-id="1f170.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f171.png" alt="" data-id="1f171.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f18e.png" alt="" data-id="1f18e.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f191.png" alt="" data-id="1f191.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f17e.png" alt="" data-id="1f17e.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f198.png" alt="" data-id="1f198.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>26d4.png" alt="" data-id="26d4.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f4db.png" alt="" data-id="1f4db.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f6ab.png" alt="" data-id="1f6ab.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>274c.png" alt="" data-id="274c.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>2b55.png" alt="" data-id="2b55.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f4a2.png" alt="" data-id="1f4a2.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>2668.png" alt="" data-id="2668.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f6b7.png" alt="" data-id="1f6b7.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f6af.png" alt="" data-id="1f6af.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f6b3.png" alt="" data-id="1f6b3.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f6b1.png" alt="" data-id="1f6b1.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f51e.png" alt="" data-id="1f51e.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f4f5.png" alt="" data-id="1f4f5.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>2757.png" alt="" data-id="2757.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>2755.png" alt="" data-id="2755.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>2753.png" alt="" data-id="2753.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>2754.png" alt="" data-id="2754.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>203c.png" alt="" data-id="203c.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>2049.png" alt="" data-id="2049.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f4af.png" alt="" data-id="1f4af.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f505.png" alt="" data-id="1f505.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f506.png" alt="" data-id="1f506.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f531.png" alt="" data-id="1f531.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>303d.png" alt="" data-id="303d.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>26a0.png" alt="" data-id="26a0.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f6b8.png" alt="" data-id="1f6b8.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f530.png" alt="" data-id="1f530.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f22f.png" alt="" data-id="1f22f.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f4b9.png" alt="" data-id="1f4b9.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>2733.png" alt="" data-id="2733.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>274e.png" alt="" data-id="274e.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>2705.png" alt="" data-id="2705.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f4a0.png" alt="" data-id="1f4a0.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f300.png" alt="" data-id="1f300.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f310.png" alt="" data-id="1f310.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>24c2.png" alt="" data-id="24c2.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f3e7.png" alt="" data-id="1f3e7.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f202.png" alt="" data-id="1f202.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f6c2.png" alt="" data-id="1f6c2.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f6c3.png" alt="" data-id="1f6c3.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f6c4.png" alt="" data-id="1f6c4.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f6c5.png" alt="" data-id="1f6c5.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>267f.png" alt="" data-id="267f.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f6ad.png" alt="" data-id="1f6ad.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f6be.png" alt="" data-id="1f6be.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>2734.png" alt="" data-id="2734.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f17f.png" alt="" data-id="1f17f.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f6b0.png" alt="" data-id="1f6b0.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f6b9.png" alt="" data-id="1f6b9.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f6ba.png" alt="" data-id="1f6ba.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f6bc.png" alt="" data-id="1f6bc.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f6bb.png" alt="" data-id="1f6bb.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f6ae.png" alt="" data-id="1f6ae.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f3a6.png" alt="" data-id="1f3a6.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f4f6.png" alt="" data-id="1f4f6.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f201.png" alt="" data-id="1f201.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f196.png" alt="" data-id="1f196.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>267b.png" alt="" data-id="267b.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f197.png" alt="" data-id="1f197.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f192.png" alt="" data-id="1f192.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>2747.png" alt="" data-id="2747.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f195.png" alt="" data-id="1f195.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f193.png" alt="" data-id="1f193.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>23-20e3.png" alt="" data-id="23-20e3.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>30-20e3.png" alt="" data-id="30-20e3.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>31-20e3.png" alt="" data-id="31-20e3.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>32-20e3.png" alt="" data-id="32-20e3.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>33-20e3.png" alt="" data-id="33-20e3.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>34-20e3.png" alt="" data-id="34-20e3.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>35-20e3.png" alt="" data-id="35-20e3.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>36-20e3.png" alt="" data-id="36-20e3.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>37-20e3.png" alt="" data-id="37-20e3.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>38-20e3.png" alt="" data-id="38-20e3.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>39-20e3.png" alt="" data-id="39-20e3.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f51f.png" alt="" data-id="1f51f.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f522.png" alt="" data-id="1f522.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>25b6.png" alt="" data-id="25b6.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>23ea.png" alt="" data-id="23ea.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f500.png" alt="" data-id="1f500.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f501.png" alt="" data-id="1f501.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>23e9.png" alt="" data-id="23e9.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f502.png" alt="" data-id="1f502.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>25c0.png" alt="" data-id="25c0.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f53c.png" alt="" data-id="1f53c.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f53d.png" alt="" data-id="1f53d.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>23eb.png" alt="" data-id="23eb.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>23ec.png" alt="" data-id="23ec.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f199.png" alt="" data-id="1f199.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>27a1.png" alt="" data-id="27a1.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>2b05.png" alt="" data-id="2b05.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>2b06.png" alt="" data-id="2b06.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>2b07.png" alt="" data-id="2b07.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>2197.png" alt="" data-id="2197.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>2198.png" alt="" data-id="2198.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>2199.png" alt="" data-id="2199.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>2196.png" alt="" data-id="2196.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>2194.png" alt="" data-id="2194.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>21aa.png" alt="" data-id="21aa.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f504.png" alt="" data-id="1f504.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>21a9.png" alt="" data-id="21a9.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>2934.png" alt="" data-id="2934.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>2935.png" alt="" data-id="2935.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>2139.png" alt="" data-id="2139.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>2195.png" alt="" data-id="2195.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f524.png" alt="" data-id="1f524.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f521.png" alt="" data-id="1f521.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f520.png" alt="" data-id="1f520.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f523.png" alt="" data-id="1f523.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f3b5.png" alt="" data-id="1f3b5.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f3b6.png" alt="" data-id="1f3b6.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>3030.png" alt="" data-id="3030.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>27bf.png" alt="" data-id="27bf.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>2714.png" alt="" data-id="2714.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f503.png" alt="" data-id="1f503.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>2795.png" alt="" data-id="2795.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>2796.png" alt="" data-id="2796.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>2797.png" alt="" data-id="2797.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>2716.png" alt="" data-id="2716.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>27b0.png" alt="" data-id="27b0.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f4b2.png" alt="" data-id="1f4b2.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f4b1.png" alt="" data-id="1f4b1.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>a9.png" alt="" data-id="a9.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>ae.png" alt="" data-id="ae.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>2122.png" alt="" data-id="2122.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f51a.png" alt="" data-id="1f51a.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f519.png" alt="" data-id="1f519.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f51b.png" alt="" data-id="1f51b.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f51d.png" alt="" data-id="1f51d.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f51c.png" alt="" data-id="1f51c.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>2611.png" alt="" data-id="2611.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f518.png" alt="" data-id="1f518.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>26aa.png" alt="" data-id="26aa.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>26ab.png" alt="" data-id="26ab.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f534.png" alt="" data-id="1f534.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f535.png" alt="" data-id="1f535.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f539.png" alt="" data-id="1f539.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f538.png" alt="" data-id="1f538.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f536.png" alt="" data-id="1f536.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f537.png" alt="" data-id="1f537.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f53a.png" alt="" data-id="1f53a.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>25aa.png" alt="" data-id="25aa.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>25ab.png" alt="" data-id="25ab.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>25fc.png" alt="" data-id="25fc.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>25fb.png" alt="" data-id="25fb.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f53b.png" alt="" data-id="1f53b.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>2b1b.png" alt="" data-id="2b1b.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>2b1c.png" alt="" data-id="2b1c.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>25fe.png" alt="" data-id="25fe.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>25fd.png" alt="" data-id="25fd.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f532.png" alt="" data-id="1f532.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f533.png" alt="" data-id="1f533.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f508.png" alt="" data-id="1f508.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f509.png" alt="" data-id="1f509.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f50a.png" alt="" data-id="1f50a.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f507.png" alt="" data-id="1f507.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f4e3.png" alt="" data-id="1f4e3.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f4e2.png" alt="" data-id="1f4e2.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f514.png" alt="" data-id="1f514.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f004.png" alt="" data-id="1f004.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f515.png" alt="" data-id="1f515.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f0cf.png" alt="" data-id="1f0cf.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>2660.png" alt="" data-id="2660.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>2663.png" alt="" data-id="2663.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>2665.png" alt="" data-id="2665.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>2666.png" alt="" data-id="2666.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f3b4.png" alt="" data-id="1f3b4.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f4ad.png" alt="" data-id="1f4ad.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f4ac.png" alt="" data-id="1f4ac.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f550.png" alt="" data-id="1f550.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f551.png" alt="" data-id="1f551.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f552.png" alt="" data-id="1f552.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f553.png" alt="" data-id="1f553.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f554.png" alt="" data-id="1f554.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f555.png" alt="" data-id="1f555.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f556.png" alt="" data-id="1f556.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f557.png" alt="" data-id="1f557.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f558.png" alt="" data-id="1f558.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f559.png" alt="" data-id="1f559.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f55a.png" alt="" data-id="1f55a.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f55b.png" alt="" data-id="1f55b.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f55c.png" alt="" data-id="1f55c.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f55d.png" alt="" data-id="1f55d.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f55e.png" alt="" data-id="1f55e.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f55f.png" alt="" data-id="1f55f.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f560.png" alt="" data-id="1f560.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f561.png" alt="" data-id="1f561.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f562.png" alt="" data-id="1f562.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f563.png" alt="" data-id="1f563.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f564.png" alt="" data-id="1f564.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f565.png" alt="" data-id="1f565.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f566.png" alt="" data-id="1f566.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f567.png" alt="" data-id="1f567.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f236.png" alt="" data-id="1f236.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f250.png" alt="" data-id="1f250.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f239.png" alt="" data-id="1f239.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f21a.png" alt="" data-id="1f21a.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f232.png" alt="" data-id="1f232.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f251.png" alt="" data-id="1f251.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f238.png" alt="" data-id="1f238.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f234.png" alt="" data-id="1f234.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f233.png" alt="" data-id="1f233.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>3297.png" alt="" data-id="3297.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>3299.png" alt="" data-id="3299.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f23a.png" alt="" data-id="1f23a.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f235.png" alt="" data-id="1f235.png" /></div>