<?php

	// ########################## INCLUDE BACK-END ###########################
	require_once (dirname(dirname(dirname(__FILE__))) . DIRECTORY_SEPARATOR . 'cache' . DIRECTORY_SEPARATOR . 'data_admin_options.php');
	
	$path = $base_url . "includes/emojis/img/32/";

?>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f600.png" alt="" data-id="1f600.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f62c.png" alt="" data-id="1f62c.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f601.png" alt="" data-id="1f601.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f602.png" alt="" data-id="1f602.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f603.png" alt="" data-id="1f603.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f604.png" alt="" data-id="1f604.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f605.png" alt="" data-id="1f605.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f606.png" alt="" data-id="1f606.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f607.png" alt="" data-id="1f607.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f609.png" alt="" data-id="1f609.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f60a.png" alt="" data-id="1f60a.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>263a.png" alt="" data-id="263a.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f60b.png" alt="" data-id="1f60b.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f60c.png" alt="" data-id="1f60c.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f60d.png" alt="" data-id="1f60d.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f618.png" alt="" data-id="1f618.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f617.png" alt="" data-id="1f617.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f619.png" alt="" data-id="1f619.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f61a.png" alt="" data-id="1f61a.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f61c.png" alt="" data-id="1f61c.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f61d.png" alt="" data-id="1f61d.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f61b.png" alt="" data-id="1f61b.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f60e.png" alt="" data-id="1f60e.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f60f.png" alt="" data-id="1f60f.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f636.png" alt="" data-id="1f636.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f610.png" alt="" data-id="1f610.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f611.png" alt="" data-id="1f611.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f612.png" alt="" data-id="1f612.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f633.png" alt="" data-id="1f633.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f61e.png" alt="" data-id="1f61e.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f61f.png" alt="" data-id="1f61f.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f620.png" alt="" data-id="1f620.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f621.png" alt="" data-id="1f621.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f614.png" alt="" data-id="1f614.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f615.png" alt="" data-id="1f615.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f623.png" alt="" data-id="1f623.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f616.png" alt="" data-id="1f616.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f62b.png" alt="" data-id="1f62b.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f629.png" alt="" data-id="1f629.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f624.png" alt="" data-id="1f624.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f62e.png" alt="" data-id="1f62e.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f631.png" alt="" data-id="1f631.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f628.png" alt="" data-id="1f628.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f630.png" alt="" data-id="1f630.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f62f.png" alt="" data-id="1f62f.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f626.png" alt="" data-id="1f626.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f627.png" alt="" data-id="1f627.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f625.png" alt="" data-id="1f625.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f622.png" alt="" data-id="1f622.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f62a.png" alt="" data-id="1f62a.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f613.png" alt="" data-id="1f613.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f62d.png" alt="" data-id="1f62d.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f635.png" alt="" data-id="1f635.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f632.png" alt="" data-id="1f632.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f637.png" alt="" data-id="1f637.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f634.png" alt="" data-id="1f634.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f4a4.png" alt="" data-id="1f4a4.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f4a9.png" alt="" data-id="1f4a9.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f608.png" alt="" data-id="1f608.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f47f.png" alt="" data-id="1f47f.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f479.png" alt="" data-id="1f479.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f47a.png" alt="" data-id="1f47a.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f480.png" alt="" data-id="1f480.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f47b.png" alt="" data-id="1f47b.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f47d.png" alt="" data-id="1f47d.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f63a.png" alt="" data-id="1f63a.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f638.png" alt="" data-id="1f638.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f639.png" alt="" data-id="1f639.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f63b.png" alt="" data-id="1f63b.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f63c.png" alt="" data-id="1f63c.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f63d.png" alt="" data-id="1f63d.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f640.png" alt="" data-id="1f640.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f63f.png" alt="" data-id="1f63f.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f63e.png" alt="" data-id="1f63e.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f64c.png" alt="" data-id="1f64c.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f44f.png" alt="" data-id="1f44f.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f44b.png" alt="" data-id="1f44b.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f44d.png" alt="" data-id="1f44d.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f44e.png" alt="" data-id="1f44e.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f44a.png" alt="" data-id="1f44a.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>270a.png" alt="" data-id="270a.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>270c.png" alt="" data-id="270c.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f44c.png" alt="" data-id="1f44c.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>270b.png" alt="" data-id="270b.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f450.png" alt="" data-id="1f450.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f4aa.png" alt="" data-id="1f4aa.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f64f.png" alt="" data-id="1f64f.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>261d.png" alt="" data-id="261d.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f446.png" alt="" data-id="1f446.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f447.png" alt="" data-id="1f447.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f448.png" alt="" data-id="1f448.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f449.png" alt="" data-id="1f449.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f485.png" alt="" data-id="1f485.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f444.png" alt="" data-id="1f444.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f445.png" alt="" data-id="1f445.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f442.png" alt="" data-id="1f442.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f443.png" alt="" data-id="1f443.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f440.png" alt="" data-id="1f440.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f464.png" alt="" data-id="1f464.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f465.png" alt="" data-id="1f465.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f476.png" alt="" data-id="1f476.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f466.png" alt="" data-id="1f466.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f467.png" alt="" data-id="1f467.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f468.png" alt="" data-id="1f468.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f469.png" alt="" data-id="1f469.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f471.png" alt="" data-id="1f471.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f474.png" alt="" data-id="1f474.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f475.png" alt="" data-id="1f475.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f472.png" alt="" data-id="1f472.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f473.png" alt="" data-id="1f473.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f46e.png" alt="" data-id="1f46e.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f477.png" alt="" data-id="1f477.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f482.png" alt="" data-id="1f482.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f385.png" alt="" data-id="1f385.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f47c.png" alt="" data-id="1f47c.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f478.png" alt="" data-id="1f478.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f470.png" alt="" data-id="1f470.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f6b6.png" alt="" data-id="1f6b6.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f3c3.png" alt="" data-id="1f3c3.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f483.png" alt="" data-id="1f483.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f46f.png" alt="" data-id="1f46f.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f46b.png" alt="" data-id="1f46b.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f46c.png" alt="" data-id="1f46c.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f46d.png" alt="" data-id="1f46d.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f647.png" alt="" data-id="1f647.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f481.png" alt="" data-id="1f481.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f645.png" alt="" data-id="1f645.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f646.png" alt="" data-id="1f646.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f64b.png" alt="" data-id="1f64b.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f64e.png" alt="" data-id="1f64e.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f64d.png" alt="" data-id="1f64d.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f487.png" alt="" data-id="1f487.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f486.png" alt="" data-id="1f486.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f491.png" alt="" data-id="1f491.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f48f.png" alt="" data-id="1f48f.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f46a.png" alt="" data-id="1f46a.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f45a.png" alt="" data-id="1f45a.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f455.png" alt="" data-id="1f455.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f456.png" alt="" data-id="1f456.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f454.png" alt="" data-id="1f454.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f457.png" alt="" data-id="1f457.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f459.png" alt="" data-id="1f459.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f458.png" alt="" data-id="1f458.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f484.png" alt="" data-id="1f484.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f48b.png" alt="" data-id="1f48b.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f463.png" alt="" data-id="1f463.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f460.png" alt="" data-id="1f460.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f461.png" alt="" data-id="1f461.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f462.png" alt="" data-id="1f462.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f45e.png" alt="" data-id="1f45e.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f45f.png" alt="" data-id="1f45f.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f452.png" alt="" data-id="1f452.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f3a9.png" alt="" data-id="1f3a9.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f393.png" alt="" data-id="1f393.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f451.png" alt="" data-id="1f451.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f392.png" alt="" data-id="1f392.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f45d.png" alt="" data-id="1f45d.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f45b.png" alt="" data-id="1f45b.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f45c.png" alt="" data-id="1f45c.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f4bc.png" alt="" data-id="1f4bc.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f453.png" alt="" data-id="1f453.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f48d.png" alt="" data-id="1f48d.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f302.png" alt="" data-id="1f302.png" /></div>