<?php

	// ########################## INCLUDE BACK-END ###########################
	require_once (dirname(dirname(dirname(__FILE__))) . DIRECTORY_SEPARATOR . 'cache' . DIRECTORY_SEPARATOR . 'data_admin_options.php');
	
	$path = $base_url . "includes/emojis/img/32/";

?>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f436.png" alt="" data-id="1f436.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f431.png" alt="" data-id="1f431.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f42d.png" alt="" data-id="1f42d.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f439.png" alt="" data-id="1f439.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f430.png" alt="" data-id="1f430.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f43b.png" alt="" data-id="1f43b.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f43c.png" alt="" data-id="1f43c.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f428.png" alt="" data-id="1f428.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f42f.png" alt="" data-id="1f42f.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f42e.png" alt="" data-id="1f42e.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f437.png" alt="" data-id="1f437.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f43d.png" alt="" data-id="1f43d.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f438.png" alt="" data-id="1f438.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f419.png" alt="" data-id="1f419.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f435.png" alt="" data-id="1f435.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f648.png" alt="" data-id="1f648.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f649.png" alt="" data-id="1f649.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f64a.png" alt="" data-id="1f64a.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f412.png" alt="" data-id="1f412.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f427.png" alt="" data-id="1f427.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f426.png" alt="" data-id="1f426.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f424.png" alt="" data-id="1f424.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f423.png" alt="" data-id="1f423.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f425.png" alt="" data-id="1f425.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f43a.png" alt="" data-id="1f43a.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f417.png" alt="" data-id="1f417.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f434.png" alt="" data-id="1f434.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f41d.png" alt="" data-id="1f41d.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f41b.png" alt="" data-id="1f41b.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f40c.png" alt="" data-id="1f40c.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f41e.png" alt="" data-id="1f41e.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f41c.png" alt="" data-id="1f41c.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f40d.png" alt="" data-id="1f40d.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f422.png" alt="" data-id="1f422.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f420.png" alt="" data-id="1f420.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f41f.png" alt="" data-id="1f41f.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f421.png" alt="" data-id="1f421.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f42c.png" alt="" data-id="1f42c.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f433.png" alt="" data-id="1f433.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f40b.png" alt="" data-id="1f40b.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f40a.png" alt="" data-id="1f40a.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f406.png" alt="" data-id="1f406.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f405.png" alt="" data-id="1f405.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f403.png" alt="" data-id="1f403.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f402.png" alt="" data-id="1f402.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f414.png" alt="" data-id="1f414.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f404.png" alt="" data-id="1f404.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f42a.png" alt="" data-id="1f42a.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f42b.png" alt="" data-id="1f42b.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f418.png" alt="" data-id="1f418.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f410.png" alt="" data-id="1f410.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f40f.png" alt="" data-id="1f40f.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f411.png" alt="" data-id="1f411.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f40e.png" alt="" data-id="1f40e.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f416.png" alt="" data-id="1f416.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f400.png" alt="" data-id="1f400.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f401.png" alt="" data-id="1f401.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f413.png" alt="" data-id="1f413.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f415.png" alt="" data-id="1f415.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f429.png" alt="" data-id="1f429.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f408.png" alt="" data-id="1f408.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f407.png" alt="" data-id="1f407.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f43e.png" alt="" data-id="1f43e.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f409.png" alt="" data-id="1f409.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f432.png" alt="" data-id="1f432.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f335.png" alt="" data-id="1f335.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f384.png" alt="" data-id="1f384.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f332.png" alt="" data-id="1f332.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f333.png" alt="" data-id="1f333.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f334.png" alt="" data-id="1f334.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f331.png" alt="" data-id="1f331.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f33f.png" alt="" data-id="1f33f.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f340.png" alt="" data-id="1f340.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f38d.png" alt="" data-id="1f38d.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f38b.png" alt="" data-id="1f38b.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f343.png" alt="" data-id="1f343.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f342.png" alt="" data-id="1f342.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f341.png" alt="" data-id="1f341.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f33e.png" alt="" data-id="1f33e.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f33a.png" alt="" data-id="1f33a.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f33b.png" alt="" data-id="1f33b.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f339.png" alt="" data-id="1f339.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f33c.png" alt="" data-id="1f33c.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f337.png" alt="" data-id="1f337.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f338.png" alt="" data-id="1f338.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f344.png" alt="" data-id="1f344.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f490.png" alt="" data-id="1f490.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f330.png" alt="" data-id="1f330.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f383.png" alt="" data-id="1f383.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f41a.png" alt="" data-id="1f41a.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f30e.png" alt="" data-id="1f30e.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f30d.png" alt="" data-id="1f30d.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f30f.png" alt="" data-id="1f30f.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f315.png" alt="" data-id="1f315.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f316.png" alt="" data-id="1f316.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f317.png" alt="" data-id="1f317.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f318.png" alt="" data-id="1f318.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f311.png" alt="" data-id="1f311.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f312.png" alt="" data-id="1f312.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f313.png" alt="" data-id="1f313.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f314.png" alt="" data-id="1f314.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f31a.png" alt="" data-id="1f31a.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f31d.png" alt="" data-id="1f31d.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f31b.png" alt="" data-id="1f31b.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f31c.png" alt="" data-id="1f31c.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f31e.png" alt="" data-id="1f31e.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f319.png" alt="" data-id="1f319.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>2b50.png" alt="" data-id="2b50.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f31f.png" alt="" data-id="1f31f.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f4ab.png" alt="" data-id="1f4ab.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>2728.png" alt="" data-id="2728.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>2600.png" alt="" data-id="2600.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>26c5.png" alt="" data-id="26c5.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>2601.png" alt="" data-id="2601.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>26a1.png" alt="" data-id="26a1.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f525.png" alt="" data-id="1f525.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f4a5.png" alt="" data-id="1f4a5.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>2744.png" alt="" data-id="2744.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>26c4.png" alt="" data-id="26c4.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f4a8.png" alt="" data-id="1f4a8.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>2614.png" alt="" data-id="2614.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f4a7.png" alt="" data-id="1f4a7.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f4a6.png" alt="" data-id="1f4a6.png" /></div>
<div class="arrowchat_emoji"><img src="<?php echo $path; ?>1f30a.png" alt="" data-id="1f30a.png" /></div>